config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :description, presence: true

  after_create :push_notification


  def push_notification
    ActionCable.server.broadcast(
                          "posts",
                          post: json_view,
                          title: title
    )
  end

  def json_view
    PostsController.render(partial: "posts/posts", locals: {post: self})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js">

    </script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Agregar Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
  <tr>
    <td><%= post.title %></td>
    <td><%= post.description %></td>
    <td><%= link_to 'Show', post, class: 'btn btn-primary' %></td>
    <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-dark' %></td>
    <td><%= link_to 'Destroy', post, class:'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody id="nuevo">
    <% @posts.each do |post| %>
      <%= render 'posts/posts', post: post %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class: 'btn' %>

app/views/posts/new.html.erb
<h3 class="text-center">Nuevo Post</h3>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <br><br><br>
    <div class="card">
      <div class="card-header">Agregar Nuevo Post</div>
      <div class="card-body">
        <%= render 'form', post: @post %>
      </div>
      <div class="card-footer">
        <%= link_to 'Back', posts_path %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <br><br><br>
    <div class="card">
      <div class="card-header">
        <%= @post.title %>
      </div>
      <div class="card-body">
        <%= @post.description %>
      </div>
      <div class="card-footer">
        <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Back', posts_path %>
      </div>
    </div>
  </div>
</div>